[build]
  base = "project"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/supabase/*"
  to = "https://gacgollaafyecysczbs.supabase.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
