[build]
  base = "project"
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
